[build]
  base = "packages/web/"
  command = "npm run build"
  publish = "public"
  environment = { NODE_VERSION = "20.11.1" }

[context.staging.environment]
  NODE_ENV = "development"

[context.preview.environment]
  NODE_ENV = "development"
